#15 Scrapers for joker and Jpoint(2018-2019)
confeti/confeti pull request #29
Opened 2020-11-26 16:18 UTC by AstralRomance

Close #15 
Requirements in confeti_scraper/requirements.txt
Output jsons in confeti_scraper/output/valid_output
Run all scrapers and postprocessing with run_spiders.py

2020-11-29 18:12 UTC, marsofandrew commented
As I know it's a compiled file `scraper/confeti_scraper/confeti_scraper/__pycache__/__init__.cpython-36.pyc`

2020-11-29 18:13 UTC, marsofandrew commented
And also `scraper/confeti_scraper/confeti_scraper/__pycache__/settings.cpython-36.pyc` and the same `*3.pyc` file

2020-11-29 18:51 UTC, marsofandrew requested changes
See comments

2020-12-01 15:29 UTC, AstralRomance commented
pycaches removed.

2020-12-03 15:30 UTC, marsofandrew commented on scraper/confeti_scraper/confeti_scraper/run_spiders.py
> +run_scrapers()
add new line

2020-12-03 15:30 UTC, marsofandrew commented on scraper/confeti_scraper/confeti_scraper/spiders/joker2018_scraper.py
> +        yield self.conference
add new line

2020-12-03 15:30 UTC, marsofandrew commented on scraper/confeti_scraper/scrapy.cfg
> +shell = ipython
add new line

2020-12-03 15:30 UTC, marsofandrew commented on scraper/confeti_scraper/confeti_scraper/spiders/jpoint_scraper.py
> +        yield self.conference
please add new line

2020-12-04 20:23 UTC, marsofandrew approved these changes

2020-12-04 21:27 UTC, merged